### ISSUE TITLE
Emulating accessories 

### ISSUE THREAD

**Issue by L-Castelli-BR** [madhephaestus/WiiChuck#2]
Hello guys!

I do love GH, but I hate the guitar.
I’m looking to a way to emulate a guitar to my WiiMote using arduino.

basically do the inverse of what you did. But I have zero experience with such kind of code. Do you have interest in it?

Best Regards,
Lucas

**Comment by madhephaestus** [comment]
sorry, thats a bit too far out of scope of this library
