### ISSUE TITLE
Classic controller 

### ISSUE THREAD

**Issue by 20161220-rootfest** [madhephaestus/WiiChuck#3]
how can i read the value of the left joystick on classic controller ? 

Serial.println joyYLeftBytes();

is not working

**Comment by madhephaestus** [comment]
controllerObject.getJoyYLeft() is the function. Make sure you are using the object, it's not a static method.

**Comment by 20161220-rootfest** [comment]
Sorry but i dont get it to work even with

Serial.println controllerObject.getJoyYLeft();

**Comment by madhephaestus** [comment]
What did you name your controller object? Are you familiar with object oriented programming?  Is there a reason your example is written without parentheses? Did the classic controller example work?

**Comment by 20161220-rootfest** [comment]
> What did you name your controller object? 

I named it classic.getJoyYLeft(); if this is correct. 

> Are you familiar with object oriented programming?

No im not familiar with object oriented programming.

> Is there a reason your example is written without parentheses?

It dinnt work with them for me but i think i just did that wrong . Can you help me ? 

> Did the classic controller example work?

Yes

**Comment by madhephaestus** [comment]
Modify the example and in loop put two new lines:
Serial.print( "\n Joy y left value =");
Serial.print( classic.getJoyYLeft());

**Comment by 20161220-rootfest** [comment]
Thank you but this is  only working half ways it only prints the first state and then repeat it no changing values :( 


Starting WiiChuck Generic Controller Demo
 Joy y left value =31
 Joy y left value =31
 Joy y left value =31
 Joy y left value =31
 Joy y left value =31
 Joy y left value =31
 Joy y left value =31
 Joy y left value =31
 Joy y left value =31
 Joy y left value =31
 Joy y left value =31
 Joy y left value =31
 Joy y left value =31

**Comment by fraser125** [comment]
I think you are looking for a simple complete example of using this library for Classic Controller:
```
#include <WiiChuck.h>

#if defined(ARDUINO_ARCH_ESP8266)
#define SDA D2
#define SCL D1
#endif

Classic classic(SDA, SCL);
 
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  classic.begin();
}

void loop() {
  // put your main code here, to run repeatedly:
  classic.readData(); 
  int joyLeftY = classic.getJoyYLeft();
  Serial.println(joyLeftY, DEC);
}
```

The value was repeating because you weren't calling 'classic.readData(); inside the loop().

**Comment by madhephaestus** [comment]
Update to 0.0.21 and try the new Classic_Simple example
