### ISSUE TITLE
Cannot Compile Sketches

### ISSUE THREAD

**Issue by HyperbolicStudios** [madhephaestus/WiiChuck#32]
Whenever I attempt to compile one of the examples, I get the following errors:
 
C:\Users\name\Documents\Arduino\libraries\WiiChuck\src\Accessory.cpp: In member function 'boolean Accessory::_burstRead(uint8_t)':

C:\Users\name\Documents\Arduino\libraries\WiiChuck\src\Accessory.cpp:286:8: error: 'class TwoWire' has no member named 'reset'

**Comment by madhephaestus** [comment]
check 0.0.26 now
